#!/usr/bin/env bash
# Generates a MySQL dump with all databases
# and creates a compressed archive out of it.

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
